[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma db push --skip-generate && npm start"

[build.environment]
PRISMA_CLI_BINARY_TARGETS = "linux-musl"